### PR TITLE
Show documentation as hover docs

### PR DESCRIPTION
**Pull request by kirillgla**
We'll need to wait for some merge to finish and its code to arrive into the SDK before we can merge this, though

### CODE REVIEW

**Comment by kirillgla** [comment]
JFYI, the code this PR depends on has just been merged into the platform

**Comment by auduchinok** [comment]
Triggering CI test. 🙂

**Comment by drhumlen** [comment]
What does this do? Do you have a screenshot? And will it be merged?

**Comment by auduchinok** [comment]
@drhumlen Using the updated APIs so it's in better sync with other languages.

**Comment by kirillgla** [comment]
The changes are purely cosmetic, they don't change the contents of the tooltips, but only the way they render. That's what new tooltips would look like:
image
Just for the record, there are two problems with this PR:

- [ ] Incorrect background of the quick docs. [Here](https://youtrack.jetbrains.com/issue/RIDER-53042)'s a ticket representing that
- [ ] The horizontal line is too thick:
image

**Comment by auduchinok** [comment]
Closing a no longer required PR.
@kirillgla Thanks for making it work out of the box!

**Pull request closed without merging**
