### PR TITLE
Frontend: support URL navigation in string literals

### PR DESCRIPTION
**Pull request by DedSec256**
image

### CODE REVIEW

**Comment by nojaf** [comment]
Hi @DedSec256, does this open the door for https://youtrack.jetbrains.com/issue/RIDER-73590 as well?

**Comment by DedSec256** [comment]
@nojaf, for sure! :)
image

**Comment by nojaf** [comment]
Nice!

**Comment by auduchinok** [comment]
@DedSec256 There're some `TODO`s, is it OK to leave them as is?

**Comment by DedSec256** [comment]
Yes, these methods will be implemented in future PRs about injections; they are not needed for URL's

**Review by auduchinok — APPROVED** [review]

**Pull request merged**
