### PR TITLE
Psi/MemberSignature: fix typeUsage -> returnTypeInfo

### PR DESCRIPTION
**Pull request by DedSec256**
Similar to https://github.com/JetBrains/resharper-fsharp/pull/392
https://github.com/JetBrains/resharper-fsharp/blob/215b0b4febea04974f01d28555119fa679ad3adc/ReSharper.FSharp/src/FSharp.Psi.Features/src/Parsing/FSharpTreeBuilderBase.fs#L842-L853

https://github.com/JetBrains/resharper-fsharp/blob/215b0b4febea04974f01d28555119fa679ad3adc/ReSharper.FSharp/test/data/parsing/signatures/Type%20member%20-%20Member%2001.fsi.gold#L31-L49

### CODE REVIEW

**Comment by DedSec256** [comment]
image

**Comment by auduchinok** [comment]
@DedSec256 Are there any known cases where it didn't work prior to the change here and in #392? Would it be easy to have a test if yes?

**Comment by DedSec256** [comment]
@auduchinok, these problems appeared in the branch with typing assist for xmldocs; corresponding tests will be available there

**Review by auduchinok — APPROVED** [review]
Thanks!

**Pull request merged**
