### PR TITLE
Migrate F# quickdocs to the real quickdoc API

### PR DESCRIPTION
**Pull request by kirillgla**
Very long ago, quickdocs used to be implemented through the 'error description' mechanism. When I implemented proper quickdocs in Rider, I added a legacy compatibility mechanism that allowed plugins to (for the most part) keep the existing code and keep adding quickdocs through highlighters. Unfortunately, this way is very restricting: I'm pretty sure it's impossible to implement navigation using it. Also, this legacy compatibility mechanism is causing many exceptions and some race conditions in Rider. In this PR I removed the highlighter-based quickdocs and added regular ones in preparation for the removal of that compatibility mode. Conveniently, I was able to reuse most of the existing code.

### CODE REVIEW

**Comment by kirillgla** [comment]
There seems to be a compilation failure in `PsiUtil.fs(331,27)` due to `error FS0073: internal error: tcrefOfAppTy (Failure)`. This is not a file or solution I changed, so I'll assume it's not a relevant failure

**Comment by auduchinok** [comment]
> There seems to be a compilation failure in PsiUtil.fs(331,27) due to error FS0073: internal error: tcrefOfAppTy (Failure). This is not a file or solution I changed, so I'll assume it's not a relevant failure

@kirillgla Yes, there is a regression in F# compiler in .NET SDK. We've pinned an earlier version that doesn't have this issue as a workaround.

**Review by auduchinok — APPROVED** [review]
@kirillgla Thanks for migrating it! I've cleaned it up a bit and added some `null` checks. We should update some parts there too to enable things like navigation, but it could be well done separately later.

**Comment by auduchinok** [comment]
> If you need to improve F# quickdocs and feel like this API is too restrictive, making it use declared elements would be the best first step.

That would be an interesting thing to look into, yes. As for now, the tooltip/quick doc content is created by FCS, and it has no knowledge of R# declared elements. We can, however, map FCS symbols to R# declared elements for use in navigation and other features, but the core of the tooltip generation is unlikely to be migrated to logic similar to other language implementations any time soon.

**Pull request merged**
