### PR TITLE
Add empty attribute action

### PR DESCRIPTION
**Pull request by En3Tho**
Not sure if you need it actually. Lately with Inline if lambda and stuff I got a feeling that it's quite bothersome to manually type f to ([<>] f) and so on.
So this basically adds "Add empty attribute" actions to different declarations.
Feel free to close this if you don't feel like it's useful for everyone

Maybe it's just better to add specific "Add InlineIfLambda attribute" or QuickFix for ValueOption patterns. I don't know.

### CODE REVIEW

**Comment by En3Tho** [comment]
This actually needs more availability tests as I haven't included ranges to look for.

**Comment by En3Tho** [comment]
I've added tests and it seems to work as expected.

**Comment by auduchinok** [comment]
@En3Tho This looks a bit too ad-hoc solution for one specific case that ignores the bigger problem. The main problem here is not about adding the attributes list (which is just two keystrokes by its own, `[` and `<`, and may be less than `Alt+Enter`, zero or more `Down` presses and `Enter` that are proposed here). The problem is about adding parens to a pattern. There are similar cases where we want to add parens as well, like typing a typed or a tuple pattern, and we don't want to add many different actions that would separately help with various consequences of the single problem.

What _might_ work instead is implementing a similar thing via typing assists:
```fsharp

fun {caret} x -> ()

// type `[`
fun [{caret}] x -> ()

// type `<`
fun ([<{caret}>] x) -> ()
```
and similar for other cases:
```
fun a{caret} -> ()

// type `,`
fun (a,{caret}) -> ()
```
```fsharp
fun t{caret} -> ()

// type `:`
fun (t:{caret}) -> ()
```

That looks much more seamless but might be a bit less discoverable at first. At the same time it might turn out that these assists could get into way in some cases and because of that I'm not 100% sure yet we'll merge it (soon) after careful testing even though I'd personally love to have something like it.

We may discover various cases where it may be hard to find what the most expected behaviour is. An example case to consider from the top of my head is this:
```fsharp
let f x{caret}
```
Would typing `:` add parens here or not?
```fsharp
let f (x:{caret})
```
```fsharp
let f x:{caret}
```

**Comment by En3Tho** [comment]
@auduchinok Well, this one does create parens for patterns when attributes are created but this is not important.
I like your idea, although I would like parens to be generated on first non-utility keystroke, eg:
let f x = ...

let f [<{caret}>]x  - no parens
let f ([<O{caret}>]x) - now parens are created

or 

let f x:{caret} - no parens
let f (x: i{caret}) - parens

**Comment by auduchinok** [comment]
> Also, i think we could reuse intellisense

No, sadly, we can't use it here due to performance consideration. The typing assists are expected to only use lexer and (when lexer is not enough only) parser, it's not allowed to use slower name resolution here.

> and reuse this logic for other items too - this way user won't even need to write [<>] or parens, eg from this:

There're too many cases where it could easily interfere with what users might want to do here. I don't see why typing `[<` is bad enough here to justify adding new hard-to-discover workflows that may break more general ones.

**Comment by En3Tho** [comment]
@auduchinok can you explain why intellisense can't be used? Isn't it like user presses enter on intellisense item, some kind of workflow starts? Do you mean that starting this kind of workflow might slow other stuff? Or does intellisense miss this kind of callback mechanism?

**Comment by auduchinok** [comment]
> @auduchinok can you explain why intellisense can't be used? Isn't it like user presses enter on intellisense item and then some kind of workflow starts? Do you mean that starting this kind of workflow might slow other stuff? Or does intellisense miss this kind of callback mechanism?

Yes, it's because typing assists work on the main thread and using resolve from them would block other things. There're cases where other features may block things in a similar way currently, but we should be working on removing them in R#/Rider and not adding more such cases in F# plugin.

**Comment by auduchinok** [comment]
> I like your idea, although I would like parens to be generated on first non-utility keystroke, eg:

What would you want the incomplete and non-parseable code for (prior to typing the attribute name)?
```fsharp
let f [<{caret}>] x
```
Is there any other desired result that this code could be changed to afterwards, other than adding parens?

The typed pattern example where it's hard to decide whether parens are needed is also not becoming easier with that suggestion of adding the parens later:
```fsharp
let f x:{caret} - no parens
let f (x: i{caret}) - parens
```
I see two scenarios that a user could want:
* type the return type (no parens needed at all and they should not be added)
* type the type for a parameter pattern (parens needed)

All of the following have to still be easy to write with the new typing assists:
```fsharp
let f (x: int) = ()
let f x : int = ()
let f (x: int) : int = ()
```

**Comment by auduchinok** [comment]
> @auduchinok I see. Thank you. I guess this should be closed then?

Let's leave it open for a while, I'd like to go through it before closing and to see what tests cases we would probably want to have in the typing assists if we try to implement them. Thank you for speaking about the issue, it's interesting to see if it'll be easy to make it work seamless!

**Comment by En3Tho** [comment]
@auduchinok I belive I've fixed all the thing you noted except for those that are still in question. I've added those tricky stuff you've mentioned in tests like let x: [<A>] _ = 1
Please look at specifyReturnTypeInfo function, it is super quircky, sadly.
Should I add more tests?

**Pull request closed without merging**
